/**
 * ROBOT STATES
 */

// init
#define STATE_INIT 'I' 
#define STATE_INIT_DELAY 5000

// stop
#define STATE_STOP 'S'

// forward
#define STATE_FORWARD 'F'
#define STATE_FORWARD_DELAY 30

// steer
#define STATE_STEER 'X'
#define STATE_STEER_DELAY 5
#define STATE_STEER_TIMEOUT 20000

// find a way out
#define STATE_FINDWAYOUT 'W'
#define STATE_FINDWAYOUT_ANGLE 90
#define STATE_FINDWAYOUT_BLINK_DELAY 100
#define STATE_FINDWAYOUT_N_BLINK 5

// error
#define STATE_ERROR 'E'
#define STATE_ERROR_BLINK_DELAY 500
#define STATE_ERROR_N_BLINK 10


/**
 * COURSE CONTROL
 */
#define NO_COURSE -1
#define COURSE_MAX_DEVIATION 2


/**
 * SENSORS
 */ 
// ultrasonic. obstacle max distance (cm)
#define DISTANCE_OBSTACLE 30
#define DISTANCE_OBSTACLE_FINDWAYOUT 20
#define DISTANCE_OBSTACLE_ALERT 10


/**
 * SERVO MOTORS
 */
#define LEFT 0
#define RIGHT 1

#define SERVO_STOP 90
#define SERVO_RIGHT_FULL 0   // [0, 180]
#define SERVO_LEFT_FULL 180  // [180, 0]

#define SERVO_FWD_SPEED 83   
#define SERVO_STEER_SPEED 87

#define SERVO_RIGHT_FWD_INC 2
#define SERVO_LEFT_FWD_INC 0

#define SERVO_RIGHT_STEER_INC 2
#define SERVO_LEFT_STEER_INC 0

#define SERVO_RIGHT_FWD SERVO_RIGHT_FULL + SERVO_FWD_SPEED - SERVO_RIGHT_FWD_INC
#define SERVO_LEFT_FWD SERVO_LEFT_FULL - SERVO_FWD_SPEED + SERVO_LEFT_FWD_INC

#define SERVO_RIGHT_STEER SERVO_RIGHT_FULL + SERVO_STEER_SPEED - SERVO_RIGHT_STEER_INC
#define SERVO_LEFT_STEER SERVO_LEFT_FULL - SERVO_STEER_SPEED + SERVO_LEFT_STEER_INC


/**
 * DISPLAY_VALUE
 */
#define DISPLAY_VALUE(X, UNDEF) ((X != UNDEF) ? String(X):String("null")) 
