/*
 * RIGHT [0, 180]
 * LEFT [180, 0]
 * 
 * LOWER SPEED => SERVO_FWD_SPEED=88
 */

#define SERVO_STOP 90
#define SERVO_RIGHT_FULL 0
#define SERVO_LEFT_FULL 180
#define SERVO_FWD_SPEED 80
#define SERVO_STEER_SPEED 87
#define SERVO_RIGHT_INC 0
#define SERVO_LEFT_INC 3
#define SERVO_RIGHT_FWD SERVO_RIGHT_FULL + SERVO_FWD_SPEED - SERVO_RIGHT_INC
#define SERVO_LEFT_FWD SERVO_LEFT_FULL - SERVO_FWD_SPEED + SERVO_LEFT_INC
#define SERVO_RIGHT_STEER SERVO_RIGHT_FULL + SERVO_STEER_SPEED - SERVO_RIGHT_INC
#define SERVO_LEFT_STEER SERVO_LEFT_FULL - SERVO_STEER_SPEED + SERVO_LEFT_INC
